### PR TITLE
Pass thread control

### PR DESCRIPTION
**Pull request by dfischer**
Allow passThreadControl api to inbox:

https://developers.facebook.com/docs/messenger-platform/handover-protocol/pass-thread-control/#page_inbox

### CODE REVIEW

**Comment by dfischer** [comment]
Ping @paked

**Comment by paked** [comment]
Sorry for the delay!

Thanks for the PR.

**Comment by dfischer** [comment]
Shit @paked it included the change to go.mod which I had to do to test it -

**Comment by dfischer** [comment]
https://github.com/paked/messenger/blob/master/go.mod#L1 @paked needs fix :)

**Comment by paked** [comment]
Fixed

**Pull request merged**
