### PR TITLE
Add tests for event dispatching

### PR DESCRIPTION
**Pull request by dgellow**
This pull request implements unit tests for the dispatching of events by covering `(*Messenger).classify` and `(*Messenger).dispatch`.

### CODE REVIEW

**Comment by dgellow** [comment]
Relates to #1. I guess that covers the quote:
> I think it should be relatively easy to get some basic tests going

**Comment by paked** [comment]
Do you think you would be able to set up Travis CI for this (or Circle, I don't really mind)?

**Comment by dgellow** [comment]
Sure

**Comment by dgellow** [comment]
I don't have the permissions to create the travis job, you will have to do it yourself :)
But this config file should be enough.

**Comment by dgellow** [comment]
You can see the travis job for my fork, for the branch related to this PR: https://travis-ci.org/dgellow/messenger/builds/354007431

**Comment by paked** [comment]
Merged!

**Pull request merged**
