### PR TITLE
Implement support for AccountLinking process

### PR DESCRIPTION
**Pull request by dgellow**
This pull request adds a method `HandleAccountLinking` and the corresponding message type `AccountLinking`. 

As specified in the documentation about the [authentication process](https://developers.facebook.com/docs/messenger-platform/account-linking/authentication), an event [messaging_account_linking](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_account_linking) is emitted after a successful linking/unlinking action.

I tried to follow what was already existing, tell me if something should be changed.

Also, if you're interested, I have a version of the example in `cmd/bot` that demonstrates the entire account linking process. That could be quite useful for beginners I think, though the example would become more complex. I would gladly create another pull request for that purpose.

### CODE REVIEW

**Comment by paked** [comment]
It might be worth creating a example to showcase the more complex behaviour.

Maybe we could move `/cmd/bot` to `/examples/basic`, then add `/examples/linked-account` etc.

**Comment by paked** [comment]
Apart from that, LGTM.

**Comment by dgellow** [comment]
> Maybe we could move /cmd/bot to /examples/basic, then add /examples/linked-account etc.

Yes, that sounds good.

**Review by depado — APPROVED** [review]

**Comment by dgellow** [comment]
To give you an idea of the result, you have here a screenshot of a session interacting with the new bot showing the support for the account linking process.

screen shot 2018-03-15 at 21 34 34

---
And a view of the login form presented to the user during the process.

screen shot 2018-03-15 at 21 34 12

**Comment by dgellow** [comment]
For the new example I haven't used your library [github.com/paked/configure](https://github.com/paked/configure), the reason was to remove dependencies. That way the example can be built with just a `go build`. I would suggest to do the same for the `basic` example, but it's your call.

Also, when we will have a travis job setup (cf https://github.com/paked/messenger/pull/40#issuecomment-373225571), we will be able to add a step `go build ./examples/...` to ensure that PRs don't break the examples.

**Comment by paked** [comment]
OK. I've just merged the Travis PR in. I don't think I can manually trigger a build on this PR, but if you make another commit (or `git commit --amend`) it will trigger.

RE: not using configure, that's fine. If you're going down that road in this example we should probably do it in both. Would you mind removing the use of it in the basic example?

Once this is done, will merge.

**Comment by dgellow** [comment]
I rebased on master, removed `paked/configure` from the example `basic`, added the step building examples to travis config.

**Comment by dgellow** [comment]
@paked Is anything missing for this Pull Request being merged?

**Comment by paked** [comment]
Sorry for the delay, merged.

Thanks for your contribution!

**Pull request merged**
